---
title: "R Notebook"
output: html_notebook
---

This is a scraping suggestion for the following website: 
https://hansa-heemann.dvinci.de/de/jobs

```{r}
options(stringsAsFactors = FALSE)
library(xml2)
library(httr)
library(DT)
urlGen <- function(nr) 'https://hansa-heemann.dvinci.de/de/jobs'
nr <- 1
hasResult <- TRUE
output <- list()

while(hasResult){
	print(nr)
	url <- urlGen(nr)
	response <- url %>% httr::GET(add_headers(.headers = c(":method" = "GET", ":authority" = "hansa-heemann.dvinci.de", ":scheme" = "https", ":path" = "/de/jobs", "user-agent" = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36", accept = "*/*", "sec-fetch-site" = "same-origin", "sec-fetch-mode" = "cors", "sec-fetch-dest" = "empty", referer = "https://hansa-heemann.dvinci.de/de/jobs", "accept-encoding" = "gzip, deflate", "accept-language" = "de-DE,de;q=0.9,en-US;q=0.8,en;q=0.7", cookie = "_ga=GA1.2.1342415111.1593811153; JSESSIONID=72ACC8279A5433EA222BAF701A9C49F3; _gid=GA1.2.523488745.1594975022; _gat_gtag_UA_123957930_2=1"))) %>% httr::content(type = "text", encoding = "UTF-8")
	xpath <- data.frame(
		"/html/body/div/div/div/div/div/table/tbody/tr/td/a[not(descendant::*)]"
	)
	response <- tryCatch(
		expr = response %>% xml2::read_html() %>% rvest::html_nodes(xpath = as.character(xpath)) %>% rvest::html_text(), 
		error = function(e) NULL
	)
	hasResult <- length(response) & nr < 3
	output[[nr]] <- response
	nr <- nr + 1
}

output %>% 
	lapply(FUN = data.frame) %>% 
	do.call(what = rbind) %>% 
	DT::datatable()
```

```{r}
post_To_Production(host = "http://192.168.1.11")
```



Potential new fields to consider:

```{r}
#load('multicol_filt_19.RData')

library(shiny)

ui <- fluidPage(
	h3(shiny::tags$b("Suggestions for additional data to scrape.")),
	h5(shiny::tags$b("Click on columns to add/remove an xpath from the scraper.")),
	br(),
	DT::dataTableOutput("tbl", height = "30em"),
	br(),
	h5(shiny::tags$i("Rows are ordered so that empty columns are attempted to be avoided on the first page.")),
	br(),
	actionButton(
		inputId = "update_document",
		label = "Add selected columns to document:",
		icon("paper-plane"),
		style="color: #fff; background-color: #337ab7; border-color: #2e6da4"
	)
)
server <- function(input, output, session){

	observeEvent(eventExpr = input$update_document,{
		#file.remove("Notebook_Scraping.Rmd")
		root_xpath <- "/html/body/div/div/div/div/div/table/tbody/tr" 
		page_url <- "https://hansa-heemann.dvinci.de/de/jobs" 
		XPathes <- colnames(multicol_filt)[input$tbl_columns_selected + 1]
		update_document(
			XPathes = XPathes,
			root_xpath = root_xpath,
			page_url = page_url,
			selectedCol = input$tbl_columns_selected %>% sort %>% safe_deparse
)
		stopApp(returnValue = invisible())
	})

	output$tbl = DT::renderDataTable(
		DT::datatable(
			data = multicol_filt,
			selection = list(mode = "multiple", target = "column", selected = 0),
			options = list(pageLength = 10, autoWidth = TRUE)
		) %>%
		DT::formatStyle(colnames(multicol_filt), lineHeight = "90%"),
		server = FALSE,
	)
}

runApp(
	appDir = shinyApp(ui, server), 
	launch.browser = shiny::paneViewer(minHeight = "maximize")
)
```
